### ISSUE TITLE
ACTIVIDAD 2 Inforgrafia 

### ISSUE THREAD

**Issue by MarcoRg06** [SistemasTecTlaxiaco/actividad-2-infografia-MarcoRg06#1]
Nombre: Marco Uriel Rosas Garcia 1BS
[ACTIVIDAD 2 Infografia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-MarcoRg06/files/9449593/ACTIVIDAD.2.Infografia.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De acuerdo a la rúbrica, has obtenido un 17.6% del 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
